### ISSUE TITLE
fatal error: FreeRTOS.h: No such file or directory

### ISSUE THREAD

**Issue by davisgarcesn** [vacagonzalo/UM-Digitales2#1]
Se siguieron los pasos del readme.
1. Se clono repo con las carpetas demo, queue y semaphore
2. Se clono repo de FreeRTOS de manera recursiva. Se tomo en cuenta el siguiente comando "git clone https://github.com/FreeRTOS/FreeRTOS.git --recurse-submodules"
3. Se ubicaron en una misma carpeta ambos repos.
4. Se ingreso via terminal a carpeta demo y se ejecuto "make" dando error:
![image](https://user-images.githubusercontent.com/22599209/230532975-5e0ef36e-4f32-448c-abe2-e93009188819.png)
5. Se reviso codigo mostrando error de referencia de la libreria FreeRTOS:
![image](https://user-images.githubusercontent.com/22599209/230533083-f8fc4b21-bc3c-4f36-9eb0-84acc7540932.png)
7. Se intento corregir el Makefile sin exito.

S.O.: Ubuntu 22.04.2 Jammy
GCC: 11.3.0
En este terminal se han hecho pruebas de FreeRTOS con exito usando ESP-IDF

**Comment by vacagonzalo** [comment]
Hola, ¡muchas gracias por el reporte!
Voy a modificar el proyecto para que no se necesite hacer una clonación manual del repositorio de FreeRTOS.

**Comment by vacagonzalo** [comment]
hola @davisgarcesn , hice merge de los cambios que deberían hacer el trabajo más fácil.
Te pido si podrías, por favor, hacer una nueva prueba con esta nueva versión.

**Comment by davisgarcesn** [comment]
Probado. "Make" corrio bien en la carpeta y ya corri demo 01
